name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, '3.10', 3.11, 3.12, 3.13 ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
    - name: Set up Node
      uses: actions/setup-node@v4
    - name: Install chromedriver
      uses: nanasess/setup-chromedriver@master
    - name: run tests
      run: |
        pip install --upgrade pip
        pip install .[tests]
        ./misc/test.sh
